package com.utsoft.myapplication.model;

import io.realm.Realm;
import io.realm.RealmObject;
import io.realm.annotations.Ignore;
import io.realm.annotations.PrimaryKey;

/**
 * Created by wangzhu on 2017/3/3.
 * func:
 */

public class User extends RealmObject {

    private String name = "张三（默认）";
    private int age = 18;


    //    @PrimaryKey
//    int id;
    @Ignore
    private int sessionId;

    // Standard getters & setters generated by your IDE…
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getAge() {
        return age;
    }

    public void setAge(int age) {
        this.age = age;
    }

    public int getSessionId() {
        return sessionId;
    }

    public void setSessionId(int sessionId) {
        this.sessionId = sessionId;
    }

//    public int getId() {
//        return id;
//    }
//
//    public void setId(int id) {
//        this.id = id;
//    }
}